package com.ruiping.BankApp.db;



// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import de.greenrobot.dao.DaoException;

/**
 * Entity mapped to table EMP.
 */
public class Emp {

    /** Not-null value. */
    private String empId;
    private String empMobile;
    private String newPhone;
    private String empName;
    private String empCover;
    private String pushId;
    private String deviceId;
    private String channelId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient EmpDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Emp() {
    }

    public Emp(String empId) {
        this.empId = empId;
    }

    public Emp(String empId, String empMobile, String newPhone, String empName, String empCover, String pushId, String deviceId, String channelId) {
        this.empId = empId;
        this.empMobile = empMobile;
        this.newPhone = newPhone;
        this.empName = empName;
        this.empCover = empCover;
        this.pushId = pushId;
        this.deviceId = deviceId;
        this.channelId = channelId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEmpDao() : null;
    }

    /** Not-null value. */
    public String getEmpId() {
        return empId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    public String getEmpMobile() {
        return empMobile;
    }

    public void setEmpMobile(String empMobile) {
        this.empMobile = empMobile;
    }

    public String getNewPhone() {
        return newPhone;
    }

    public void setNewPhone(String newPhone) {
        this.newPhone = newPhone;
    }

    public String getEmpName() {
        return empName;
    }

    public void setEmpName(String empName) {
        this.empName = empName;
    }

    public String getEmpCover() {
        return empCover;
    }

    public void setEmpCover(String empCover) {
        this.empCover = empCover;
    }

    public String getPushId() {
        return pushId;
    }

    public void setPushId(String pushId) {
        this.pushId = pushId;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
